[general]
library_name = "mlir_c"
output_file_path = "../lib/libMLIR_h.jl"
prologue_file_path = "./missing_defs.jl"
epilogue_file_path = ""
use_julia_native_enum_type = false
use_deterministic_symbol = true
printer_blacklist = [
    "MAKE_MLIR_PYTHON_QUALNAME",
]

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = false
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = true

[codegen.macro]
macro_mode = "basic"
add_comment_for_skipped_macro = false