[general]
library_name = "mlir_c"
output_file_path = "libMLIR_h.jl"
prologue_file_path = "prologue.jl"
epilogue_file_path = ""
use_julia_native_enum_type = false
use_deterministic_symbol = true
smart_de_anonymize = true
extract_c_comment_style = "doxygen"
fold_single_line_comment = false
struct_field_comment_style = "outofline"
show_c_function_prototype = false
printer_blacklist = [
    "MAKE_MLIR_PYTHON_QUALNAME",
]
output_ignorelist = [
    "MLIR_PYTHON_API_EXPORTED",
    "MLIR_CAPI_EXPORTED",
    "MLIR_CAPI_DWARF_ADDRESS_SPACE_NULL",
    "MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS",
    "MLIR_ENABLE_PDL_IN_PATTERNMATCH",
    "MLIR_ENABLE_NVPTXCOMPILER",
    "MLIR_ENABLE_ROCM_CONVERSIONS",
    "LLVM_DEFAULT_TARGET_TRIPLE",
    "LLVM_ENABLE_THREADS",
    "LLVM_HAS_ATOMICS",
    "LLVM_HOST_TRIPLE",
    "LLVM_NATIVE_ARCH",
    "LLVM_NATIVE_ASMPARSER",
    "LLVM_NATIVE_ASMPRINTER",
    "LLVM_NATIVE_DISASSEMBLER",
    "LLVM_NATIVE_TARGET",
    "LLVM_NATIVE_TARGETINFO",
    "LLVM_NATIVE_TARGETMC",
    "LLVM_ON_UNIX",
    "LLVM_USE_INTEL_JITEVENTS",
    "LLVM_USE_OPROFILE",
    "LLVM_USE_PERF",
    "LLVM_VERSION_MAJOR",
    "LLVM_VERSION_MINOR",
    "LLVM_VERSION_PATCH",
    "LLVM_VERSION_STRING",
    "LLVM_FORCE_ENABLE_STATS",
    "LLVM_ENABLE_ZLIB",
    "LLVM_ENABLE_ZSTD",
    "LLVM_UNREACHABLE_OPTIMIZE",
    "LLVM_ENABLE_DIA_SDK",
    "LLVM_ENABLE_TELEMETRY",
    "LLVM_ENABLE_DEBUGLOC_TRACKING_COVERAGE",
    "LLVM_ENABLE_DEBUGLOC_TRACKING_ORIGIN",
    "INT64_MAX",
    "INT64_MIN",
    "UINT64_MAX",
    # types can't be versioned just like functions
    "MlirTypeID",
    "MlirTypeIDAllocator",
    "MlirLlvmThreadPool",
    "MlirStringRef",
    "MlirLogicalResult",
    "MlirContext",
    "MlirDialect",
    "MlirDialectHandle",
    "MlirDialectRegistry",
    "MlirOperation",
    "MlirOpOperand",
    "MlirOpPrintingFlags",
    "MlirBlock",
    "MlirRegion",
    "MlirSymbolTable",
    "MlirAttribute",
    "MlirIdentifier",
    "MlirLocation",
    "MlirModule",
    "MlirType",
    "MlirValue",
    "MlirNamedAttribute",
    "MlirOperationState",
    "MlirAffineExpr",
    "MlirAffineMap",
    "MlirPass",
    "MlirExternalPass",
    "MlirPassManager",
    "MlirOpPassManager",
    "MlirExternalPassCallbacks",
    "MlirDiagnostic",
    "MlirExecutionEngine",
    "MlirIntegerSet",
    "MlirAsmState",
    "MlirBytecodeWriterConfig",
]

[codegen]
use_julia_bool = true
always_NUL_terminated_string = true
is_function_strictly_typed = false
opaque_func_arg_as_PtrCvoid = false
opaque_as_mutable_struct = true
use_ccall_macro = true

[codegen.macro]
macro_mode = "basic"
add_comment_for_skipped_macro = false